# Generated by Django 4.2.7 on 2024-02-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('width', models.IntegerField(verbose_name='ширина')),
                ('height', models.IntegerField(verbose_name='высота')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('place', models.CharField(max_length=255, verbose_name='расположнение')),
                ('is_active', models.BooleanField(default=False, verbose_name='активно')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='surfaces', verbose_name='изображение')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_surface.surface')),
            ],
        ),
    ]
